# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

# --- Sitios a monitorizar ---
sites:
  - name: coregistros.com
    url: https://www.coregistros.com
    expectedStatusCodes: [200, 201-299, 301-308]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: mitest.de
    url: https://mitest.de
    expectedStatusCodes: [200, 201-299, 301-308]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: bevrand.com
    url: https://www.bevrand.com
    expectedStatusCodes: [200, 201-299, 301-308]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: milopciones.es
    url: https://milopciones.es
    expectedStatusCodes: [200, 201-299, 301-308]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: g0crm.info (API WP)
    url: https://www.g0crm.info/wp-login.php
    expectedStatusCodes: [200, 201-299, 301-308]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: blog.sorteopremios.com
    url: https://blog.sorteopremios.com
    expectedStatusCodes: [200, 201-299, 301-308]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: daily.g0crm.com
    url: https://daily.g0crm.com
    expectedStatusCodes: [200, 201-299, 301-308, 401-404]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: crm.g0crm.com
    url: https://crm.g0crm.com/robots.txt
    expectedStatusCodes: [200, 201-299, 301-308]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: sorteopremios.com
    url: https://sorteopremios.com
    expectedStatusCodes: [200, 201-299, 301-308]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: admin.coregistros.com
    url: https://admin.coregistros.com/login.php
    expectedStatusCodes: [200, 201-299, 301-308]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: go.coregistros.com
    url: https://go.coregistros.com
    expectedStatusCodes: [200, 201-299, 301-308]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: go.mitest.de
    url: https://go.mitest.de
    expectedStatusCodes: [200, 201-299, 301-308]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: api2.g0crm.com
    url: https://api2.g0crm.com
    expectedStatusCodes: [200, 201-299, 301-308]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: api3.g0crm.com
    url: https://api3.g0crm.com/openapi.json
    expectedStatusCodes: [200, 201-299, 301-308]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: app.milopciones.es
    url: https://app.milopciones.es
    expectedStatusCodes: [200, 201-299, 301-308, 401-404]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: go.bevrand.com
    url: https://go.bevrand.com
    expectedStatusCodes: [200, 201-299, 301-308]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: go.topcausas.org
    url: https://go.topcausas.org
    expectedStatusCodes: [200, 201-299, 301-308]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: leadcure.coregistros.com
    url: https://leadcure.coregistros.com
    expectedStatusCodes: [200, 201-299, 301-308]
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe


# --- (Opcional) Web de estado ---
status-website:
  name: Estado de Servicios – Coregistros
  theme: dark
  # baseUrl: /<nombre-del-repo>     # si usas GitHub Pages de proyecto
  # baseUrl: /                      # si usas dominio propio en Pages
  # logoUrl: https://coregistros.com/path/logo.png
  # favicon: https://coregistros.com/path/favicon-32x32.png


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
